version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-thumbs:latest
    container_name: image-resizer-backend-1  # Match the actual container name
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thumb.rule=Host(`24short.ru`)"
      - "traefik.http.routers.thumb.entrypoints=websecure"
      - "traefik.http.routers.thumb.tls.certresolver=le"
      - "traefik.http.services.thumb.loadbalancer.server.port=8000"
      # Add HTTP redirect
      - "traefik.http.routers.thumb-http.rule=Host(`24short.ru`)"
      - "traefik.http.routers.thumb-http.entrypoints=web"
      - "traefik.http.routers.thumb-http.middlewares=https-redirect"
    networks:
      - web

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Certificate resolver with exact name "le"
      - --certificatesresolvers.le.acme.email=valery@directorii.com
      - --certificatesresolvers.le.acme.storage=/acme/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --log.level=DEBUG  # Enable debug for troubleshooting
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/acme
    networks:
      - web
    labels:
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  web:
    driver: bridge
    external: false
